package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallPlatform;
import org.linlinjava.litemall.db.domain.LitemallPlatformExample;
import org.linlinjava.litemall.db.domain.LitemallPlatformWithBLOBs;

public interface LitemallPlatformMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    long countByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int insert(LitemallPlatformWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int insertSelective(LitemallPlatformWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPlatform selectOneByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPlatformWithBLOBs selectOneByExampleSelective(@Param("example") LitemallPlatformExample example, @Param("selective") LitemallPlatformWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPlatformWithBLOBs selectOneByExampleWithBLOBs(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallPlatformWithBLOBs> selectByExampleSelective(@Param("example") LitemallPlatformExample example, @Param("selective") LitemallPlatformWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    List<LitemallPlatformWithBLOBs> selectByExampleWithBLOBs(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    List<LitemallPlatform> selectByExample(LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPlatformWithBLOBs selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallPlatformWithBLOBs.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    LitemallPlatformWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallPlatformWithBLOBs selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallPlatformWithBLOBs record, @Param("example") LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallPlatformWithBLOBs record, @Param("example") LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallPlatform record, @Param("example") LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallPlatformWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallPlatformWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallPlatformExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}