package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQwfbArticleAttach;
import org.linlinjava.litemall.db.domain.LitemallQwfbArticleAttachExample;

public interface LitemallQwfbArticleAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    long countByExample(LitemallQwfbArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQwfbArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int insert(LitemallQwfbArticleAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQwfbArticleAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleAttach selectOneByExample(LitemallQwfbArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleAttach selectOneByExampleSelective(@Param("example") LitemallQwfbArticleAttachExample example, @Param("selective") LitemallQwfbArticleAttach.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallQwfbArticleAttach> selectByExampleSelective(@Param("example") LitemallQwfbArticleAttachExample example, @Param("selective") LitemallQwfbArticleAttach.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    List<LitemallQwfbArticleAttach> selectByExample(LitemallQwfbArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleAttach selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallQwfbArticleAttach.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    LitemallQwfbArticleAttach selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleAttach selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQwfbArticleAttach record, @Param("example") LitemallQwfbArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQwfbArticleAttach record, @Param("example") LitemallQwfbArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQwfbArticleAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQwfbArticleAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallQwfbArticleAttachExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_attach
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long id);
}