package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQwfbArticleDetail;
import org.linlinjava.litemall.db.domain.LitemallQwfbArticleDetailExample;

public interface LitemallQwfbArticleDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    long countByExample(LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int insert(LitemallQwfbArticleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQwfbArticleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleDetail selectOneByExample(LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleDetail selectOneByExampleSelective(@Param("example") LitemallQwfbArticleDetailExample example, @Param("selective") LitemallQwfbArticleDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleDetail selectOneByExampleWithBLOBs(LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallQwfbArticleDetail> selectByExampleSelective(@Param("example") LitemallQwfbArticleDetailExample example, @Param("selective") LitemallQwfbArticleDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    List<LitemallQwfbArticleDetail> selectByExampleWithBLOBs(LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    List<LitemallQwfbArticleDetail> selectByExample(LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleDetail selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallQwfbArticleDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    LitemallQwfbArticleDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticleDetail selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQwfbArticleDetail record, @Param("example") LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallQwfbArticleDetail record, @Param("example") LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQwfbArticleDetail record, @Param("example") LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQwfbArticleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallQwfbArticleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQwfbArticleDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallQwfbArticleDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long id);
}