package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallArticleCategory;
import org.linlinjava.litemall.db.domain.LitemallArticleCategoryExample;

public interface LitemallArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    long countByExample(LitemallArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int insert(LitemallArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int insertSelective(LitemallArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleCategory selectOneByExample(LitemallArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleCategory selectOneByExampleSelective(@Param("example") LitemallArticleCategoryExample example, @Param("selective") LitemallArticleCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallArticleCategory> selectByExampleSelective(@Param("example") LitemallArticleCategoryExample example, @Param("selective") LitemallArticleCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    List<LitemallArticleCategory> selectByExample(LitemallArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallArticleCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    LitemallArticleCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallArticleCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallArticleCategory record, @Param("example") LitemallArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallArticleCategory record, @Param("example") LitemallArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_article_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}