package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallUserAdvice;
import org.linlinjava.litemall.db.domain.LitemallUserAdviceExample;

public interface LitemallUserAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    long countByExample(LitemallUserAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallUserAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int insert(LitemallUserAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int insertSelective(LitemallUserAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserAdvice selectOneByExample(LitemallUserAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserAdvice selectOneByExampleSelective(@Param("example") LitemallUserAdviceExample example, @Param("selective") LitemallUserAdvice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallUserAdvice> selectByExampleSelective(@Param("example") LitemallUserAdviceExample example, @Param("selective") LitemallUserAdvice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    List<LitemallUserAdvice> selectByExample(LitemallUserAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserAdvice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallUserAdvice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    LitemallUserAdvice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallUserAdvice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallUserAdvice record, @Param("example") LitemallUserAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallUserAdvice record, @Param("example") LitemallUserAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallUserAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallUserAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallUserAdviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_user_advice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}