package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQwfbAccountGroup;
import org.linlinjava.litemall.db.domain.LitemallQwfbAccountGroupExample;

public interface LitemallQwfbAccountGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    long countByExample(LitemallQwfbAccountGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQwfbAccountGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int insert(LitemallQwfbAccountGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQwfbAccountGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbAccountGroup selectOneByExample(LitemallQwfbAccountGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbAccountGroup selectOneByExampleSelective(@Param("example") LitemallQwfbAccountGroupExample example, @Param("selective") LitemallQwfbAccountGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallQwfbAccountGroup> selectByExampleSelective(@Param("example") LitemallQwfbAccountGroupExample example, @Param("selective") LitemallQwfbAccountGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    List<LitemallQwfbAccountGroup> selectByExample(LitemallQwfbAccountGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbAccountGroup selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallQwfbAccountGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    LitemallQwfbAccountGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbAccountGroup selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQwfbAccountGroup record, @Param("example") LitemallQwfbAccountGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQwfbAccountGroup record, @Param("example") LitemallQwfbAccountGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQwfbAccountGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQwfbAccountGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallQwfbAccountGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_account_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}