package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallQwfbArticle;
import org.linlinjava.litemall.db.domain.LitemallQwfbArticleExample;

public interface LitemallQwfbArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    long countByExample(LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int insert(LitemallQwfbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int insertSelective(LitemallQwfbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticle selectOneByExample(LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticle selectOneByExampleSelective(@Param("example") LitemallQwfbArticleExample example, @Param("selective") LitemallQwfbArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticle selectOneByExampleWithBLOBs(LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<LitemallQwfbArticle> selectByExampleSelective(@Param("example") LitemallQwfbArticleExample example, @Param("selective") LitemallQwfbArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    List<LitemallQwfbArticle> selectByExampleWithBLOBs(LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    List<LitemallQwfbArticle> selectByExample(LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticle selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") LitemallQwfbArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    LitemallQwfbArticle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    LitemallQwfbArticle selectByPrimaryKeyWithLogicalDelete(@Param("id") Long id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallQwfbArticle record, @Param("example") LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") LitemallQwfbArticle record, @Param("example") LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallQwfbArticle record, @Param("example") LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallQwfbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(LitemallQwfbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallQwfbArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") LitemallQwfbArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_qwfb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Long id);
}