package org.linlinjava.litemall.db.domain;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;

public class LitemallPlatformWithBLOBs extends LitemallPlatform implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform.url_rules
     *
     * @mbg.generated
     */
    private String urlRules;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column litemall_platform.category_rules
     *
     * @mbg.generated
     */
    private String categoryRules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform.url_rules
     *
     * @return the value of litemall_platform.url_rules
     *
     * @mbg.generated
     */
    public String getUrlRules() {
        return urlRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform.url_rules
     *
     * @param urlRules the value for litemall_platform.url_rules
     *
     * @mbg.generated
     */
    public void setUrlRules(String urlRules) {
        this.urlRules = urlRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column litemall_platform.category_rules
     *
     * @return the value of litemall_platform.category_rules
     *
     * @mbg.generated
     */
    public String getCategoryRules() {
        return categoryRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column litemall_platform.category_rules
     *
     * @param categoryRules the value for litemall_platform.category_rules
     *
     * @mbg.generated
     */
    public void setCategoryRules(String categoryRules) {
        this.categoryRules = categoryRules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", urlRules=").append(urlRules);
        sb.append(", categoryRules=").append(categoryRules);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LitemallPlatformWithBLOBs other = (LitemallPlatformWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getShortName() == null ? other.getShortName() == null : this.getShortName().equals(other.getShortName()))
            && (this.getDes() == null ? other.getDes() == null : this.getDes().equals(other.getDes()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getExtraDes() == null ? other.getExtraDes() == null : this.getExtraDes().equals(other.getExtraDes()))
            && (this.getLoginUrl() == null ? other.getLoginUrl() == null : this.getLoginUrl().equals(other.getLoginUrl()))
            && (this.getHomeUrl() == null ? other.getHomeUrl() == null : this.getHomeUrl().equals(other.getHomeUrl()))
            && (this.getPublishArticleUrl() == null ? other.getPublishArticleUrl() == null : this.getPublishArticleUrl().equals(other.getPublishArticleUrl()))
            && (this.getPublishVideoUrl() == null ? other.getPublishVideoUrl() == null : this.getPublishVideoUrl().equals(other.getPublishVideoUrl()))
            && (this.getPublishPicsUrl() == null ? other.getPublishPicsUrl() == null : this.getPublishPicsUrl().equals(other.getPublishPicsUrl()))
            && (this.getArticlesUrl() == null ? other.getArticlesUrl() == null : this.getArticlesUrl().equals(other.getArticlesUrl()))
            && (this.getPicsUrl() == null ? other.getPicsUrl() == null : this.getPicsUrl().equals(other.getPicsUrl()))
            && (this.getVideosUrl() == null ? other.getVideosUrl() == null : this.getVideosUrl().equals(other.getVideosUrl()))
            && (this.getSorted() == null ? other.getSorted() == null : this.getSorted().equals(other.getSorted()))
            && (this.getAddTime() == null ? other.getAddTime() == null : this.getAddTime().equals(other.getAddTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()))
            && (this.getUrlRules() == null ? other.getUrlRules() == null : this.getUrlRules().equals(other.getUrlRules()))
            && (this.getCategoryRules() == null ? other.getCategoryRules() == null : this.getCategoryRules().equals(other.getCategoryRules()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_platform
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getShortName() == null) ? 0 : getShortName().hashCode());
        result = prime * result + ((getDes() == null) ? 0 : getDes().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getExtraDes() == null) ? 0 : getExtraDes().hashCode());
        result = prime * result + ((getLoginUrl() == null) ? 0 : getLoginUrl().hashCode());
        result = prime * result + ((getHomeUrl() == null) ? 0 : getHomeUrl().hashCode());
        result = prime * result + ((getPublishArticleUrl() == null) ? 0 : getPublishArticleUrl().hashCode());
        result = prime * result + ((getPublishVideoUrl() == null) ? 0 : getPublishVideoUrl().hashCode());
        result = prime * result + ((getPublishPicsUrl() == null) ? 0 : getPublishPicsUrl().hashCode());
        result = prime * result + ((getArticlesUrl() == null) ? 0 : getArticlesUrl().hashCode());
        result = prime * result + ((getPicsUrl() == null) ? 0 : getPicsUrl().hashCode());
        result = prime * result + ((getVideosUrl() == null) ? 0 : getVideosUrl().hashCode());
        result = prime * result + ((getSorted() == null) ? 0 : getSorted().hashCode());
        result = prime * result + ((getAddTime() == null) ? 0 : getAddTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        result = prime * result + ((getUrlRules() == null) ? 0 : getUrlRules().hashCode());
        result = prime * result + ((getCategoryRules() == null) ? 0 : getCategoryRules().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table litemall_platform
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        name("name", "name", "VARCHAR", true),
        shortName("short_name", "shortName", "VARCHAR", false),
        des("des", "des", "VARCHAR", false),
        status("status", "status", "INTEGER", true),
        extraDes("extra_des", "extraDes", "VARCHAR", false),
        loginUrl("login_url", "loginUrl", "VARCHAR", false),
        homeUrl("home_url", "homeUrl", "VARCHAR", false),
        publishArticleUrl("publish_article_url", "publishArticleUrl", "VARCHAR", false),
        publishVideoUrl("publish_video_url", "publishVideoUrl", "VARCHAR", false),
        publishPicsUrl("publish_pics_url", "publishPicsUrl", "VARCHAR", false),
        articlesUrl("articles_url", "articlesUrl", "VARCHAR", false),
        picsUrl("pics_url", "picsUrl", "VARCHAR", false),
        videosUrl("videos_url", "videosUrl", "VARCHAR", false),
        sorted("sorted", "sorted", "INTEGER", false),
        addTime("add_time", "addTime", "TIMESTAMP", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        deleted("deleted", "deleted", "BIT", false),
        urlRules("url_rules", "urlRules", "LONGVARCHAR", false),
        categoryRules("category_rules", "categoryRules", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table litemall_platform
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}