server:
  port: 8089
  
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    password: 123456 

dubbo:
  application:
    name: message
    qosEnable: true
    qosPort: 33333
    qosAcceptForeignIp: false
  registry:
    address: redis://127.0.0.1:6379
    username: root
    password: 123456
  protocol:
    name: dubbo
    port: 20881
  scan.base-packages: org.linlinjava.litemall.message
  annotation:
    package: org.linlinjava.litemall.message
#  scan.base-package: org.linlinjava.litemall.message

wss:
  server:
    host: localhost
    port: 16379
    timeout: 1800000
  origin:
    host: localhost    

         