server:
  port: 8089
  
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    password: 123456 

embedded.zookeeper.port: 2181

dubbo:
  application:
    name: message
    qosEnable: true
    qosPort: 33333
    qosAcceptForeignIp: false
  registry:
#    address: zookeeper://127.0.0.1:2181
    address: redis://127.0.0.1:6379
    username: root
    password: 123456
    timeout: 10000
  protocol:
    name: dubbo
    port: 20881
    serialization: kryo
  provider:
    wait: 10000
  scan.base-packages: org.linlinjava.litemall.message
  annotation:
    package: org.linlinjava.litemall.message
#  scan.base-package: org.linlinjava.litemall.message

redis:
  host: localhost
  port: 6379
  timeout: 1800000
  password: 123456

wss:
  server:
    host: localhost
    port: 16379
    timeout: 1800000
  origin:
    host: localhost    
