server:
  port: 8089
  
spring:
  dubbo:
    application:
      name: message
      qosEnable: true
      qosPort: 33333
      qosAcceptForeignIp: false
    registry:
      address: redis://127.0.0.1:6379
      username: root
      password: 123456
    scan: org.linlinjava.litemall.message
    protocol:
      name: dubbo
      port: 20881
      serialization: kryo
  redis:
    host: localhost
    port: 6379
    timeout: 1800000
    password: 123456 
    
wss:
  server:
    host: localhost
    port: 16379
    timeout: 1800000
  origin:
    host: localhost    

         